# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 2
console_title_template: "{{if .Root }}Adm: {{end}}{{ .Folder }}"
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: session
        style: diamond
        leading_diamond: ""
        background: "#073642"
        foreground: "#859900"
        template: "{{if .Root}}<#dc322f> </>{{ else }} {{ end }}{{ .UserName }} "

      - type: path
        style: plain
        background: "#839496"
        foreground: "#073642"
        properties:
          style: full
          folder_separator_icon: "󰿟"
          home_icon: "~"
        template: "<parentBackground></>  {{ .Path }} "